#!/usr/bin/env python3
"""
TI IWR6843 radar reader — tested with IWR6843AOPEVM on mmWaveICBOOST.

Hardware setup
--------------
1. Plug IWR6843AOPEVM onto the mmWaveICBOOST high-speed connector.
2. Set the SOP mode switch (S1 on ICBOOST) to position 4:
       SOP2 = 1 (switch 3 ON), SOP1 = 0, SOP0 = 0
   This runs the firmware already flashed on the EVM (OOB demo).
3. Connect the ICBOOST USB cable to your PC.
4. In Device Manager → Ports (COM & LPT) two XDS110 ports appear:
       XDS110 Class Application/User UART  → RADAR_CONFIG_PORT (115200 baud)
       XDS110 Class Auxiliary Data Port    → RADAR_DATA_PORT   (921600 baud)
   The config port always has the LOWER COM port number.
5. Point the radar at the subject's torso/hip at ~1–1.5 m range.
   The radar Y axis = forward (range) = our AP axis.

Serial ports connect to the IWR6843 over two serial ports:
  - Config port  (115200 baud): sends chirp configuration commands
  - Data port    (921600 baud): receives TLV frames

Each frame is timestamped with time.perf_counter() on receipt and placed
into a thread-safe queue as a RadarFrame namedtuple.

TLV types parsed:
  - Type 1: Detected point cloud (x, y, z, doppler)  — ~4 cm range quantisation
  - Type 2: Range profile magnitude                   — used for sub-bin centroid (~5 mm)
  - Type 5: Range-Doppler heatmap (for micro-Doppler accumulation)
"""

import struct
import threading
import time
import logging
from collections import namedtuple
from queue import Queue, Full

import numpy as np
import serial

logger = logging.getLogger(__name__)

# ── TLV constants ────────────────────────────────────────────────────────────
MAGIC_WORD = b'\x02\x01\x04\x03\x06\x05\x08\x07'
HEADER_FMT = '<Q4I3H2I'   # magic(8) ver(4) len(4) platform(4) frame_num(4)
                           # time_cpu_cycles(4) num_obj(2) num_tlvs(2) subframe(2)
                           # (note: some SDK versions differ slightly — adjust if needed)
HEADER_SIZE = 40           # bytes
TLV_HEADER_FMT = '<II'     # type(4) length(4)
TLV_HEADER_SIZE = 8

TLV_POINT_CLOUD  = 1
TLV_RANGE_PROF   = 2
TLV_RANGE_DOPPLER = 5

DSP_CLOCK_HZ = 600e6  # IWR6843 C674x DSP clock

# ── Data structures ──────────────────────────────────────────────────────────
Point = namedtuple('Point', ['x', 'y', 'z', 'doppler'])

RadarFrame = namedtuple('RadarFrame', [
    'host_ts',        # float: time.perf_counter() at first byte received
    'frame_number',   # int
    'cpu_cycles',     # int: DSP timestamp (monotonic within session)
    'points',         # list[Point] – detected point cloud (CFAR, ~4 cm quantised)
    'range_profile',  # np.ndarray shape (N,) float32, or None
    'range_doppler',  # np.ndarray shape (N_range, N_doppler) float32, or None
    'subject_range_m',# float: subject range from range-profile centroid (~5 mm precision), or NaN
])


# ── Range resolution from the DEFAULT_CONFIG below ───────────────────────────
# freqSlope = 100 MHz/μs,  numSamples = 224,  sampleRate = 7000 ksps
# B = 100e6 * 224/7000e3 = 3.2 GHz   →   range_res = c/(2B) ≈ 4.69 cm
# With centroid extraction on the range profile we achieve ~5 mm precision.
RANGE_RES_M   = 0.0469   # metres per range bin  (update if profileCfg changes)
RANGE_MIN_M   = 0.30     # ignore bins closer than this (near-field clutter)
RANGE_MAX_M   = 4.00     # ignore bins beyond this (unlikely to be the subject)

# ── Default chirp configuration — IWR6843AOP on mmWaveICBOOST ────────────────
# Generated by TI mmWave Visualizer 3.6.0.0 for xWR68xx_AOP, SDK 3.05.
# ~30 Hz frame rate (16 loops × 33.333 ms), ~4.69 cm range resolution, up to 9 m.
# IWR6843AOP: TX0+TX1 = azimuth, TX2 = elevation; all 3 TX active.
#
# Key AOP-specific commands (required by Cfg_IsAllCfgReceived() in this firmware):
#   aoaFovCfg   — angle-of-arrival field of view (AOP firmware mandatory)
#   cfarFovCfg  — range and velocity FOV limits  (AOP firmware mandatory, ×2)
#   calibData   — calibration data flag           (AOP firmware mandatory)
#
# compRangeBiasAndRxChanPhase uses alternating 1 0 -1 0 pattern for AOP antenna phasing.
# clutterRemoval is DISABLED: it converges on a stationary subject and subtracts them,
#   causing _centroid_range() to return NaN perpetually. DC offset is handled by
#   mean-centering in the stabilogram instead.
DEFAULT_CONFIG = [
    "sensorStop",
    "flushCfg",
    "dfeDataOutputMode 1",
    "channelCfg 15 7 0",           # 4 RX, 3 TX (AOP: TX0+TX1 azimuth, TX2 elevation)
    "adcCfg 2 1",
    "adcbufCfg -1 0 1 1 1",
    "profileCfg 0 60 304 7 40 0 0 100 1 224 7000 0 0 158",
    # profileCfg: id startFreq(GHz) idleTime adcStart rampEnd txPwr txPhase
    #             slope(MHz/us) txStart numSamples sampleRate hpf1 hpf2 rxGain
    # slope=100 MHz/μs, 224 samples @ 7000 ksps → B=3.2 GHz → res=4.69 cm
    "chirpCfg 0 0 0 0 0 0 0 1",   # chirp 0 → TX0
    "chirpCfg 1 1 0 0 0 0 0 2",   # chirp 1 → TX1
    "chirpCfg 2 2 0 0 0 0 0 4",   # chirp 2 → TX2 (elevation)
    "frameCfg 0 2 16 0 33.333 1 0",  # chirps 0–2, 16 loops, 33.333 ms period → 30 Hz
    "lowPower 0 0",
    "guiMonitor -1 1 1 0 0 0 1",  # enable: point cloud, range profile, R-D heatmap
    "cfarCfg -1 0 2 8 4 3 0 15 1",
    "cfarCfg -1 1 0 4 2 3 1 15 1",
    "multiObjBeamForming -1 1 0.5",
    "clutterRemoval -1 0",
    "calibDcRangeSig -1 0 -5 8 256",
    "extendedMaxVelocity -1 0",
    "lvdsStreamCfg -1 0 0 0",
    "compRangeBiasAndRxChanPhase 0.0 1 0 -1 0 1 0 -1 0 1 0 -1 0 1 0 -1 0 1 0 -1 0 1 0 -1 0",
    # AOP antenna phasing: alternating 1 0 -1 0 pattern (not identity 1 0 1 0...)
    "measureRangeBiasAndRxChanPhase 0 1.5 0.2",
    "CQRxSatMonitor 0 3 4 99 0",
    "CQSigImgMonitor 0 111 4",
    "analogMonitor 0 0",
    "aoaFovCfg -1 -90 90 -90 90",   # AOP required: full azimuth + elevation FoV
    "cfarFovCfg -1 0 0 8.40",        # AOP required: range FoV 0–8.4 m
    "cfarFovCfg -1 1 -1.21 1.21",    # AOP required: velocity FoV ±1.21 m/s
    "calibData 0 0 0",               # AOP required: no external calibration data
    "sensorStart",
]


class RadarReader:
    """
    Reads TLV frames from the IWR6843 data UART in a background thread.

    Usage
    -----
    reader = RadarReader(config_port='COM3', data_port='COM4')
    reader.start()
    frame = reader.queue.get(timeout=1.0)   # RadarFrame
    reader.stop()
    """

    def __init__(
        self,
        config_port: str,
        data_port: str,
        config_baud: int = 115200,
        data_baud: int = 921600,
        config_commands: list[str] | None = None,
        queue_size: int = 128,
    ):
        self.config_port = config_port
        self.data_port = data_port
        self.config_baud = config_baud
        self.data_baud = data_baud
        self.config_commands = config_commands or DEFAULT_CONFIG
        self.queue: Queue[RadarFrame] = Queue(maxsize=queue_size)

        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None
        self._ser_data: serial.Serial | None = None
        self._ser_cfg: serial.Serial | None = None

        # Statistics
        self.frames_received = 0
        self.frames_dropped = 0
        self.parse_errors = 0

        # Person tracker — EMA of the subject's range across frames
        # NaN until first confident detection; reset after tracker_age_max seconds
        # without a detection.
        self._person_y: float = float('nan')   # metres
        self._person_ts: float = 0.0           # host_ts of last detection

    # ── Public API ────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Open serial ports, send config, start background reader thread."""
        self._configure()
        self._stop_event.clear()
        self._thread = threading.Thread(target=self._read_loop, daemon=True, name='RadarReader')
        self._thread.start()
        logger.info("RadarReader started on data port %s", self.data_port)

    def stop(self) -> None:
        """Signal the reader thread to stop and close serial ports."""
        self._stop_event.set()
        if self._thread:
            self._thread.join(timeout=3.0)
        self._close_ports()
        logger.info(
            "RadarReader stopped. frames_received=%d dropped=%d parse_errors=%d",
            self.frames_received, self.frames_dropped, self.parse_errors,
        )

    # ── Configuration ─────────────────────────────────────────────────────────

    def _wait_for_prompt(self, prompt: str = 'mmwDemo:/>', timeout: float = 3.0) -> str:
        """
        Read from the config UART until the CLI prompt appears or timeout expires.

        Using a fixed time.sleep() + read_all() races against firmware processing
        time — if 'Done' arrives after the window, the next command is sent before
        the firmware is ready, leaving the configuration incomplete and causing
        sensorStart to fail with 'Full configuration must be provided'.
        """
        resp = ''
        deadline = time.time() + timeout
        while time.time() < deadline:
            n = self._ser_cfg.in_waiting
            if n:
                resp += self._ser_cfg.read(n).decode(errors='ignore')
                if prompt in resp:
                    break
            else:
                time.sleep(0.005)   # 5 ms poll — fast enough to catch all responses
        return resp

    def _configure(self) -> None:
        """Open the config UART, send all chirp-config commands, then open the data port."""
        self._ser_cfg = serial.Serial(self.config_port, self.config_baud, timeout=2)
        time.sleep(0.3)
        self._ser_cfg.reset_input_buffer()   # discard stale bytes from any prior session

        n_cmds = len(self.config_commands)
        print(f"[Radar] Sending {n_cmds} config commands to {self.config_port} ...")
        failed = []
        for i, cmd in enumerate(self.config_commands, 1):
            self._ser_cfg.write((cmd + '\n').encode())
            resp = self._wait_for_prompt(timeout=3.0)

            # Classify response so we can spot timing / missing-command issues
            if 'Done' in resp:
                status = 'OK '
            elif 'Error' in resp:
                status = 'ERR'
                logger.warning("Config command '%s' returned: %s", cmd, resp.strip())
                failed.append(cmd)
            else:
                status = 'T/O'  # timed out — firmware never sent 'Done' or 'Error'

            name = cmd.split()[0]
            print(f"  {i:2d}/{n_cmds}  {name:<40s} {status}")
            if status != 'OK ':
                # Print the raw response to help diagnose the issue
                print(f"         response: {repr(resp.strip()[:200])}")

        if failed:
            print(f"[Radar] WARNING: {len(failed)} command(s) returned errors: {failed}")
        elif any('T/O' in str(s) for s in []):   # placeholder — T/O counted above
            pass
        else:
            print(f"[Radar] All {n_cmds} config commands accepted (see OK/ERR/T/O above)")

        self._ser_data = serial.Serial(self.data_port, self.data_baud, timeout=1)
        logger.info("IWR6843 configured and sensor started")

    def _close_ports(self) -> None:
        for port in (self._ser_data, self._ser_cfg):
            if port and port.is_open:
                try:
                    port.close()
                except Exception:
                    pass

    # ── Read loop ─────────────────────────────────────────────────────────────

    def _read_loop(self) -> None:
        buf = bytearray()
        while not self._stop_event.is_set():
            try:
                chunk = self._ser_data.read(self._ser_data.in_waiting or 1)
                if not chunk:
                    continue
                buf.extend(chunk)
                buf = self._drain_frames(buf)
            except serial.SerialException as exc:
                logger.error("Serial read error: %s", exc)
                break

    def _drain_frames(self, buf: bytearray) -> bytearray:
        """Extract and process all complete frames from the buffer."""
        while True:
            magic_pos = buf.find(MAGIC_WORD)
            if magic_pos == -1:
                # No magic word — keep last 7 bytes in case it straddles a read
                return bytearray(buf[-7:]) if len(buf) >= 7 else buf
            if magic_pos > 0:
                buf = buf[magic_pos:]  # discard bytes before magic word

            if len(buf) < HEADER_SIZE:
                return buf  # wait for more data

            # Parse header to get total packet length
            try:
                header = self._parse_header(bytes(buf[:HEADER_SIZE]))
            except struct.error:
                self.parse_errors += 1
                buf = buf[len(MAGIC_WORD):]  # skip this magic word
                continue

            total_len = header['packet_len']
            if len(buf) < total_len:
                return buf  # wait for rest of packet

            # Timestamp at first byte of this frame
            host_ts = time.perf_counter()

            packet = bytes(buf[:total_len])
            buf = buf[total_len:]

            try:
                frame = self._parse_frame(packet, header, host_ts)
                self._enqueue(frame)
            except Exception as exc:
                self.parse_errors += 1
                logger.debug("Frame parse error: %s", exc)

        return buf

    # ── Parsing ───────────────────────────────────────────────────────────────

    @staticmethod
    def _parse_header(data: bytes) -> dict:
        """
        Parse the 40-byte frame header.

        Field layout (little-endian):
          magic          8 bytes
          version        4 bytes
          packet_len     4 bytes
          platform       4 bytes
          frame_number   4 bytes
          cpu_cycles     4 bytes  (DSP timestamp)
          num_objects    4 bytes
          num_tlvs       4 bytes
          subframe_num   4 bytes
          (total = 40 bytes; the remaining 4 bytes are padding in some SDK versions)
        """
        fields = struct.unpack_from('<8sIIIIIIII', data)
        return {
            'magic':        fields[0],
            'version':      fields[1],
            'packet_len':   fields[2],
            'platform':     fields[3],
            'frame_number': fields[4],
            'cpu_cycles':   fields[5],
            'num_objects':  fields[6],
            'num_tlvs':     fields[7],
            'subframe_num': fields[8],
        }

    def _parse_frame(self, packet: bytes, header: dict, host_ts: float) -> RadarFrame:
        offset = HEADER_SIZE
        num_tlvs = header['num_tlvs']

        points = []
        range_profile = None
        range_doppler = None

        for _ in range(num_tlvs):
            if offset + TLV_HEADER_SIZE > len(packet):
                break
            tlv_type, tlv_len = struct.unpack_from(TLV_HEADER_FMT, packet, offset)
            offset += TLV_HEADER_SIZE
            tlv_data = packet[offset: offset + tlv_len]
            offset += tlv_len

            if tlv_type == TLV_POINT_CLOUD:
                points = self._parse_points(tlv_data)
            elif tlv_type == TLV_RANGE_PROF:
                range_profile = self._parse_range_profile(tlv_data)
            elif tlv_type == TLV_RANGE_DOPPLER:
                range_doppler = self._parse_range_doppler(tlv_data)

        # ── Detect person, then refine ───────────────────────────────────────
        # Step 1: cluster CFAR point cloud → identify which range the person
        #         occupies (angle + Doppler discrimination — rejects static objects).
        # Step 2: narrow the range-profile centroid to ±0.30 m around that cluster
        #         → ~5 mm precision without tracking furniture.
        # Fallback: if no CFAR cluster found, use the full-window range-profile
        #           centroid (brightest reflector in [RANGE_MIN_M, RANGE_MAX_M]).
        person_coarse = (self._find_person_cluster(points, host_ts)
                         if points else float('nan'))

        if range_profile is not None:
            if np.isfinite(person_coarse):
                subject_range_m = self._centroid_range(
                    range_profile, center_m=person_coarse, search_r=0.30)
            else:
                subject_range_m = self._centroid_range(range_profile)
        elif np.isfinite(person_coarse):
            subject_range_m = person_coarse   # no range profile — use cluster centroid
        else:
            subject_range_m = float('nan')

        self.frames_received += 1
        return RadarFrame(
            host_ts=host_ts,
            frame_number=header['frame_number'],
            cpu_cycles=header['cpu_cycles'],
            points=points,
            range_profile=range_profile,
            range_doppler=range_doppler,
            subject_range_m=subject_range_m,
        )

    @staticmethod
    def _centroid_range(
        range_prof: np.ndarray,
        range_res: float = RANGE_RES_M,
        min_r: float = RANGE_MIN_M,
        max_r: float = RANGE_MAX_M,
        center_m: float | None = None,
        search_r: float = 0.30,
        half_window: int = 4,
    ) -> float:
        """
        Sub-bin range estimation from log-magnitude range profile.

        1. Window the profile to [min_r, max_r].
           If center_m is given, narrow to [center_m - search_r, center_m + search_r]
           so we refine around the cluster the person was detected in, not the
           globally brightest reflector (which may be furniture).
        2. Find the peak bin (brightest target in window).
        3. Compute a weighted centroid over ±half_window bins around the peak.

        Returns subject range in metres with ~5 mm precision,
        or NaN if no target is found in the window.
        """
        if center_m is not None:
            min_r = max(min_r, center_m - search_r)
            max_r = min(max_r, center_m + search_r)
        n = len(range_prof)
        bins = np.arange(n, dtype=np.float64)
        ranges = bins * range_res

        # Mask to expected subject range
        mask = (ranges >= min_r) & (ranges <= max_r)
        if not mask.any():
            return float('nan')

        windowed = range_prof.astype(np.float64)
        windowed[~mask] = 0.0

        peak_bin = int(np.argmax(windowed))
        if windowed[peak_bin] == 0.0:
            return float('nan')

        # Centroid window around peak
        lo = max(0, peak_bin - half_window)
        hi = min(n - 1, peak_bin + half_window) + 1
        w = range_prof[lo:hi].astype(np.float64)
        w = np.maximum(w - w.min(), 0.0)   # baseline-subtract to sharpen centroid
        if w.sum() == 0.0:
            return float(peak_bin * range_res)

        centroid_bin = float(np.dot(w, np.arange(lo, hi)) / w.sum())
        return centroid_bin * range_res

    @staticmethod
    def _parse_points(data: bytes) -> list[Point]:
        """Each point: x(f32), y(f32), z(f32), doppler(f32) = 16 bytes."""
        n = len(data) // 16
        pts = []
        for i in range(n):
            x, y, z, d = struct.unpack_from('<4f', data, i * 16)
            pts.append(Point(x, y, z, d))
        return pts

    @staticmethod
    def _parse_range_profile(data: bytes) -> np.ndarray:
        """Range profile: N × uint16 (log-magnitude). Return as float32."""
        n = len(data) // 2
        arr = np.frombuffer(data, dtype=np.uint16, count=n).astype(np.float32)
        return arr

    @staticmethod
    def _parse_range_doppler(data: bytes, n_range: int = 224, n_doppler: int = 16) -> np.ndarray:
        """
        Range-Doppler heatmap: n_range × n_doppler uint16 values.
        Shape returned: (n_range, n_doppler) float32.
        n_range and n_doppler must match your chirp config ADC samples and chirps/frame.
        Defaults match DEFAULT_CONFIG: profileCfg numSamples=224, frameCfg loops=16.
        """
        expected = n_range * n_doppler * 2
        if len(data) < expected:
            # Infer dimensions from actual data length
            total = len(data) // 2
            n_range = int(np.sqrt(total * 4))   # heuristic; caller should override
            n_doppler = total // n_range
        arr = np.frombuffer(data, dtype=np.uint16).astype(np.float32)
        arr = arr[:n_range * n_doppler].reshape(n_range, n_doppler)
        return arr

    # ── Person detection ──────────────────────────────────────────────────────

    @staticmethod
    def _cluster_points(
        points: list,
        eps: float = 0.35,
        min_samples: int = 2,
    ) -> list:
        """
        DBSCAN clustering on CFAR point cloud in the (x, y) plane.

        Returns a list of clusters; each cluster is a list of Point objects.
        Noise points (DBSCAN label -1) are discarded.

        Uses scipy.spatial.cKDTree — no sklearn dependency.
        eps controls the neighbourhood radius in metres (~0.35 m comfortably
        groups reflections from a single person while separating objects ≥0.5 m apart).
        """
        n = len(points)
        if n < min_samples:
            return []

        try:
            from scipy.spatial import cKDTree
        except ImportError:
            # scipy unavailable — treat all points as one cluster
            return [list(points)]

        xy = np.array([[p.x, p.y] for p in points], dtype=np.float32)
        tree = cKDTree(xy)
        neighbors = tree.query_ball_point(xy, eps)

        labels = np.full(n, -1, dtype=np.int32)
        cid = 0
        for i in range(n):
            if labels[i] != -1:
                continue
            if len(neighbors[i]) < min_samples:
                continue
            # BFS flood-fill
            queue = [i]
            labels[i] = cid
            while queue:
                seed = queue.pop()
                for nb in neighbors[seed]:
                    if labels[nb] == -1:
                        labels[nb] = cid
                        if len(neighbors[nb]) >= min_samples:
                            queue.append(nb)
            cid += 1

        clusters = []
        for c in range(cid):
            idx = np.where(labels == c)[0]
            clusters.append([points[i] for i in idx])
        return clusters

    def _find_person_cluster(
        self,
        points: list,
        host_ts: float,
        doppler_min: float = 0.04,      # m/s — minimum mean |doppler| to count as "moving"
        tracker_age_max: float = 2.0,   # s   — forget tracker after this long without detection
        ema_alpha: float = 0.25,        # EMA weight applied to each new measurement
    ) -> float:
        """
        Identify the person in the CFAR point cloud using clustering + Doppler gating.

        Algorithm
        ---------
        1. DBSCAN-cluster the point cloud in (x, y) — separates spatially distinct objects.
        2. Score each cluster:
              score = 4.0 × mean(|doppler|)        moving object → likely person
                    + 0.15 × n_points              more points → larger reflector
                    + 1.5 × proximity_to_prior      Gaussian proximity to last known range
        3. Accept the top-scoring cluster if it has Doppler ≥ doppler_min OR a valid prior.
           (A perfectly still person is held by the tracker; an unknown static blob is rejected.)
        4. Update an EMA tracker so brief stationary moments (breath-hold, pause) don't
           lose the lock.

        Returns the person's forward range y (metres), or NaN if person not identified.
        """
        clusters = self._cluster_points(points)
        if not clusters:
            return float('nan')

        tracker_valid = (np.isfinite(self._person_y) and
                         (host_ts - self._person_ts) < tracker_age_max)

        best_score = -1.0
        best_y = float('nan')
        best_dop = 0.0

        for cluster in clusters:
            ys   = np.array([p.y           for p in cluster], dtype=np.float64)
            dops = np.array([abs(p.doppler) for p in cluster], dtype=np.float64)
            cy       = float(ys.mean())
            mean_dop = float(dops.mean())
            n_pts    = len(cluster)

            # Gaussian proximity bonus: σ = 0.5 m (full weight at same location,
            # half-weight at ~0.59 m, near-zero beyond 1.5 m)
            prox = (float(np.exp(-((cy - self._person_y) ** 2) / 0.5))
                    if tracker_valid else 0.0)

            score = mean_dop * 4.0 + n_pts * 0.15 + prox * 1.5
            if score > best_score:
                best_score = score
                best_y = cy
                best_dop = mean_dop

        # Reject if static AND no prior (can't identify person among furniture)
        if best_dop < doppler_min and not tracker_valid:
            logger.debug("Person detection: all clusters static and no prior — skipping")
            return float('nan')

        # Update EMA tracker
        if tracker_valid:
            self._person_y = (1.0 - ema_alpha) * self._person_y + ema_alpha * best_y
        else:
            self._person_y = best_y   # cold start — take first moving cluster as truth
        self._person_ts = host_ts

        return float(self._person_y)

    def _enqueue(self, frame: RadarFrame) -> None:
        try:
            self.queue.put_nowait(frame)
        except Full:
            self.frames_dropped += 1
            try:
                self.queue.get_nowait()   # drop oldest
                self.queue.put_nowait(frame)
            except Exception:
                pass


# ── Utilities ─────────────────────────────────────────────────────────────────

def radar_ap_sway(frames: list[RadarFrame]) -> np.ndarray:
    """
    Extract the AP (range) sway signal from a list of RadarFrames.

    Uses range-profile centroid (subject_range_m, ~5 mm precision) when available,
    falling back to point-cloud y-median (~4 cm CFAR quantisation) otherwise.
    Frames with no detection are linearly interpolated.
    """
    values = []
    for f in frames:
        if np.isfinite(f.subject_range_m):
            values.append(f.subject_range_m)
        elif f.points:
            values.append(np.mean([p.y for p in f.points]))
        else:
            values.append(np.nan)
    arr = np.array(values, dtype=np.float64)
    # Linear interpolation over NaN gaps
    nans = np.isnan(arr)
    if nans.any() and not nans.all():
        x = np.arange(len(arr))
        arr[nans] = np.interp(x[nans], x[~nans], arr[~nans])
    return arr


def radar_doppler_signal(frames: list[RadarFrame]) -> np.ndarray:
    """
    Aggregate Doppler signal per frame: mean absolute Doppler across all points.
    Useful as a 1-D motion signal for cross-correlation temporal calibration.
    """
    values = []
    for f in frames:
        if f.points:
            values.append(np.mean([abs(p.doppler) for p in f.points]))
        else:
            values.append(0.0)
    return np.array(values, dtype=np.float64)
